# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  working_directory: ~/ratpack
  docker:
    - image: circleci/openjdk:8-jdk
  environment:
    TERM: dumb
    _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
    GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx1g"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-gradle-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "gradle/dependencies.gradle" }}
            - v1-gradle-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-{{ .Branch }}
            - v1-gradle-master
            - v1-gradle

      - run:
          name: Download Gradle Dependencies
          command: ./gradlew downloadDependencies

      # run sanity check
      - run:
          name: Run Sanity Check
          command: ./gradlew sanityCheck --max-workers=2 --build-cache

      - run:
          name: Test & Build
          command: ./gradlew build jacocoReport --continue --max-workers=2 --build-cache -PpublishToSlack

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "gradle/dependencies.gradle" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - run:
          name: Upload Coverage Results
          command: bash <(curl -s https://codecov.io/bash)
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit

      - persist_to_workspace:
          root: ~/ratpack
          paths:
            - build/*

  uploadArtifacts:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: ~/build

      - run:
          name: Upload Artifacts
          command: ./gradlew artifactoryPublish --max-workers=1 :ratpack-site:deployToHeroku -PbuildInfo.build.number=${CIRCLE_BUILD_NUM}

  deploySite:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: ~/build

      - run:
          name: Deploy Site
          command: ./gradlew :ratpack-site:deployToHeroku --max-workers=1 --build-cache

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - uploadArtifacts:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploySite:
          requires:
            - build
          filters:
            branches:
              only: master
